name: 'Setup LCOV'
author: 'Hrishikesh Kadam <hrkadam.92@gmail.com>'
description: 'Composite GitHub Action to setup LCOV.'

inputs:
  ref:
    description: |
      'Git reference like branch or tag of linux-test-project/lcov repository. '
      'Use HEAD for the default branch. '
      'Empty for stable versions.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install LCOV
      run: |
        $GITHUB_ACTION_PATH/src/install-lcov.sh \
          ${{ inputs.ref }}
      shell: bash

    - run: lcov --version
      shell: bash

branding:
  icon: 'play-circle'
  color: 'blue'
