name: 'Setup LCOV'
author: 'Hrishikesh Kadam <hrkadam.92@gmail.com>'
description: 'Composite GitHub Action to setup LCOV.'

inputs:
  install-head-version:
    description: 'Install HEAD version of linux-test-project/lcov repository'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install LCOV
      run: $GITHUB_ACTION_PATH/src/install-lcov.sh ${{ inputs.install-head-version }}
      shell: bash

    - run: lcov --version
      shell: bash

branding:
  icon: 'play-circle'
  color: 'blue'
