# Note: jobs of ci.yml and ci-dispatch.yml should be in sync
name: ci-dispatch

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner OS'
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-24.04
          - macos-latest
          - windows-latest

jobs:
  test-setup-lcov:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup LCOV
        uses: ./
      - run: lcov --version
        shell: bash
      - run: lcov --version
        shell: pwsh
      - run: lcov --version
        if: runner.os == 'Windows'
        shell: cmd
      - run: lcov --version
        if: runner.os == 'Windows'
        shell: powershell
