name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - latest-lcov

jobs:
  test-setup-lcov:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-latest, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup LCOV
        uses: ./
      - run: lcov --version
      - uses: actions/checkout@v4
        with:
          repository: linux-test-project/lcov
      - run: ./bin/lcov --version
      - run: make install
      - run: type -a lcov
      - run: lcov --version
